version: '3'

services:
    app:
        build: ./docker/apache
        ports:
            - 8080:80
        volumes:
            - ./site:/var/www/html
        links:
            - db:postgres

    db:
        image: postgres:15.4-bullseye
        volumes:
            - ./docker/data/postgres/data:/var/lib/postgresql/data
            - ./sql/ARTChive.sql:/docker-entrypoint-initdb.d/ARTChive.sql
            - ./sql/procedures.sql:/docker-entrypoint-initdb.d/procedures.sql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=changeme
            - POSTGRES_USER=postgres
            - POSTGRES_DB=ARTChive

            
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:7.6
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres@local.int
            PGADMIN_DEFAULT_PASSWORD: changeme
            PG_DATABASE: simple-course
            PG_USER: postgres
            PG_PASSWORD: changeme
        volumes:
            - ./docker/pgadmin:/root/.pgadmin
        ports:
            - 8081:80
        links:
            - db:postgres